# Generated by Django 4.1.2 on 2022-12-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_mashalachicken'),
    ]

    operations = [
        migrations.CreateModel(
            name='tavadhosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half', models.IntegerField()),
                ('full', models.IntegerField()),
            ],
        ),
    ]
