# Generated by Django 4.1.2 on 2023-04-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_registerresturant'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerResturantNewModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantName', models.CharField(max_length=50)),
                ('ownerName', models.CharField(max_length=50)),
                ('GSTNumber', models.CharField(max_length=50)),
                ('FSSAINumber', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('PhoneNo', models.CharField(max_length=50)),
                ('UserName', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
    ]
